### ISSUE TITLE
Get error: cannot join current thread. On app.stop() in example code

### ISSUE THREAD

**Issue by fonger900** [bakatrouble/pytgvoip_pyrogram#2]
When i executed your example incoming call code, the callee discarded the incoming call, then i got this error:

> D/tgvoip: Left VoIPController::~VoIPController
> call ended
> cannot join current thread
> Traceback (most recent call last):
>   File "/home/vagrant/.local/lib/python3.5/site-packages/pyrogram/client/ext/dispatcher.py", line 160, in update_worker
>     handler.callback(self.client, *args)
>   File "/home/vagrant/.local/lib/python3.5/site-packages/tgvoip_pyrogram/outgoing_call.py", line 56, in process_update
>     super(VoIPOutgoingCall, self).process_update(_, update, users, chats)
>   File "/home/vagrant/.local/lib/python3.5/site-packages/tgvoip_pyrogram/base_call.py", line 81, in process_update
>     self.call_discarded()
>   File "/home/vagrant/.local/lib/python3.5/site-packages/tgvoip_pyrogram/base_call.py", line 157, in call_discarded
>     self.call_ended()
>   File "/home/vagrant/.local/lib/python3.5/site-packages/tgvoip_pyrogram/base_call.py", line 141, in call_ended
>     self.stop()
>   File "/home/vagrant/.local/lib/python3.5/site-packages/tgvoip_pyrogram/base_call.py", line 133, in stop
>     callable(handler) and handler(self)
>   File "main.py", line 22, in call_ended
>     app.stop()
>   File "/home/vagrant/.local/lib/python3.5/site-packages/pyrogram/client/client.py", line 366, in stop
>     self.dispatcher.stop()
>   File "/home/vagrant/.local/lib/python3.5/site-packages/pyrogram/client/ext/dispatcher.py", line 106, in stop
>     worker.join()
>   File "/usr/lib/python3.5/threading.py", line 1051, in join
>     raise RuntimeError("cannot join current thread")
> RuntimeError: cannot join current thread
> 

please help.

**Comment by stefanodelbosco** [comment]
Hi,
I had your same problem.
I solved it by adding a line like this.

> voip_service = VoIPFileStreamService(client, receive_calls=False)
> call = voip_service.start_call('xxxxxxxxxxx')
> call.play('input.raw')
> call.play_on_hold(['input.raw'])
> call.set_output_file('output.raw')
> client.idle() #<--- 

In my opinion it was a problem that the client closes before the end of the call.
I hope I helped you out.

Stefano
